export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const JOBS_FETCH = 'JOBS_FETCH'
export const JOBS_REQUEST = 'JOBS_REQUEST'
export const JOBS_SUCCESS = 'JOBS_SUCCESS'
export const JOBS_FAILURE = 'JOBS_FAILURE'

export const JOBS_QUERY = 'JOBS_QUERY'
export const JOBS_QUERY_SUCCESS = 'JOBS_QUERY_SUCCESS'
export const JOBS_QUERY_FAILURE = 'JOBS_QUERY_FAILURE'

export const RESUME_FETCH = 'RESUME_FETCH'
export const RESUME_REQUEST = 'RESUME_REQUEST'
export const RESUME_SUCCESS = 'RESUME_SUCCESS'
export const RESUME_FAILURE = 'RESUME_FAILURE'

export const RESUME_UPDATE_REQUEST = 'RESUME_UPDATE_REQUEST'
export const RESUME_UPDATE_SUCCESS = 'RESUME_UPDATE_SUCCESS'
export const RESUME_UPDATE_FAILURE = 'RESUME_UPDATE_FAILURE'

export const INFORMATION_FETCH = 'INFORMATION_FETCH'
export const INFORMATION_REQUEST = 'INFORMATION_REQUEST'
export const INFORMATION_SUCCESS = 'INFORMATION_SUCCESS'
export const INFORMATION_FAILURE = 'INFORMATION_FAILURE'

export const HOME_REQUEST = 'HOME_REQUEST'
export const HOME_SUCCESS = 'HOME_SUCCESS'
export const HOME_FAILURE = 'HOME_FAILURE'

export const PAGINATION_REQUEST = 'PAGINATION_REQUEST'
export const PAGINATION_SUCCESS = 'PAGINATION_SUCCESS'
export const PAGINATION_FAILURE = 'PAGINATION_FAILURE'
